name: build

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'

jobs:
  build:
    name: Vivarium Build
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        version: ['7.4', '8.0', '8.1', '8.2']

    steps:
      - name: Source checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        id: setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          coverage: xdebug

      - name: Restore Composer cache
        id: restore-composer-cache
        uses: actions/cache/restore@v3
        with:
          path: vendor
          key: ${{ runner.OS }}-${{ matrix.version }}-composer-${{ hashFiles('**/composer.json') }}

      - name: Composer install
        id: composer
        run: composer install -o -n --prefer-dist

      - name: Create directories
        run: |
          mkdir cache
          mkdir cache/phpcs
          mkdir cache/infection
          mkdir cache/phpunit
          mkdir tests-results
          mkdir tests-results/infection
          mkdir tests-results/phpcs
          mkdir tests-results/phpmd
          mkdir tests-results/phpstan
          mkdir tests-results/phpunit

      - name: Restore Tools cache
        id: restore-tools-cache
        uses: actions/cache/restore@v3
        with:
          path: cache
          key: ${{ runner.OS }}-${{ matrix.version }}-cache-${{ hashFiles('**/composer.json') }}

      - name: Run Code Sniffer
        if: > 
          (success() || failure())
          && steps.composer.conclusion == 'success'
        run: composer phpcs

      - name: Run Mess Detector
        if: >
          (success() || failure())
          && steps.composer.conclusion == 'success'
        run: composer phpmd

      - name: Run PHPStan
        if: >
          (success() || failure())
          && steps.composer.conclusion == 'success'
        run: composer phpstan

      - name: Run Psalm
        if: >
          (success() || failure())
          && steps.composer.conclusion == 'success'
        run: composer psalm

      - name: Run PHPUnit
        id: phpunit
        if: >
          (success() || failure())
          && steps.composer.conclusion == 'success'
        run: composer phpunit

      - name: Run Infection
        if: >
          (success() || failure())
          && steps.phpunit.conclusion == 'success'
        run: composer infection

      - name: Save Composer cache
        uses: actions/cache/save@v3
        if: >
          (success() || failure())
          && steps.composer.conclusion == 'success'
        with:
          path: vendor
          key: ${{ steps.restore-composer-cache.outputs.cache-primary-key }}

      - name: Save Tools cache
        uses: actions/cache/save@v3
        if: >
          (success() || failure())
        with:
          path: cache
          key: ${{ steps.restore-tools-cache.outputs.cache-primary-key }}

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: tests-results-${{ matrix.version }}
          path: tests-results/
          if-no-files-found: ignore
          retention-days: 1
